stages:
  download:
    cmd: python stages/01_download.py
    deps:
      - stages/01_download.py
    outs:
      - download/ALL_GNPS.json
  build:
    cmd: python stages/02_build.py
    deps:
      - stages/02_build.py
      - download/ALL_GNPS.json
    outs:
      - brick/data.parquet
